### ISSUE TITLE
floxEnv: support nested packages

### ISSUE THREAD

**Issue by mkenigs** [flox/floxpkgs#79]
floxEnvs currently do not support nested packages, and the current format for `flox.nix` is ambiguous, as there's no way to differentiate between:
A nested package: `nixpkgs-flox.python3Packages.requests = { version = "1.12" };`
and
A packge with configuration: `nixpkgs-flox.VSCode.settings = { key = "value"; }`

cc @tomberek

**Comment by mkenigs** [comment]
Some options:
1. Only permit nested settings behind a reserved word like `config` or `__config`
`nixpkgs-flox.VSCode = { config = { settings = { key = "value" }; }; };`
1. Quote nested attrPaths: `nixpkgs-flox."python3Packages.requests" = { version = "1.12" };`
    - seems pretty straightforward and simple
    - nested quoting could get kinda gnarly, e.g. `"python3Packages.\"package with space\""`
1. Check if `lib.isDerivation` is true as you simultaneously recurse into the channel
    - Possible strange behavior if your channel changes
    - How would you handle derivations in passthru?
1. Require an attrPath for nested packages
`requests = { attrPath.python3Packages.requests = {}; version = "1.12"; };`
1. Nest channel in package config, and stop recursing when channel is reached:
`python3Packages.requests = { channel = "nixpkgs-flox"; version = "1.12" }`
    - makes the happy path (I want to install multiple packages from nixpkgs-flox) inconvenient
1. Whenever something is ambiguous, require some other flag to mark the end of recursion. e.g. `package = true`:
`nixpkgs-flox.python3Packages.requests = { package = true; version = "1.12" };`
`nixpkgs-flox.VSCode = { package = true; settings = { key = "value" }; };`
    - feels too dynamic and complicated

**Comment by notgne2** [comment]
To me 1 seems the most ideal, though it is semantically a bit weird and the practical concern of that reserved word being in common with something nested a user may want.

Maybe instead we could prefix both nesting and config? like `nixpkgs-flox.nested.python3Packages.requests = { version = "1.12" };` (would probably need to think of a better word) and `nixpkgs-flox.VSCode.config.settings = { key = "value"; }`. I can see some reasons to be against that though and if that wouldn't work I'd choose option 1 as-is.

**Comment by mkenigs** [comment]
What's the advantage of doing both? We could let a non-nested package avoid `config` being a reserved word?

**Comment by notgne2** [comment]
I realized we'd also have to put the `nested` prefix at every step of the way too (so more like `nixpkgs-flox.nested.python3Packages.nested.requests = { version = "1.12" };`), so that would actually be super painful.

If I did `nixpkgs-flox.coolconfig.config.system.build.toplevel = { version = "1"; }` it would think I'm just configuring `nixpkgs-flox.coolconfig` with `system = { build.toplevel = { version = "1"; }; }`. I don't think we're going to have any nixos configurations in our catalog, but it might come up in other places too maybe.

**Comment by mkenigs** [comment]
Yeah, I think that's uncommon enough that having a single reserved word is still probably the best option. And in the example you gave, we'd still support `nixpkgs-flox.coolconfig.config.config.system.build.toplevel = { version = "1"; }`. Beautiful? No. Functional? Yes.

**Comment by mkenigs** [comment]
@tomberek one other thing I've heard you mention is that you don't want stability to be a special case, but rather just part of the default prefix or something, but I'm not sure how we'd differentiate between someStability.package (we don't prepend the default prefix) and python3Packages.requests (we do need to prepend the default prefix). Unless we start checking for what exists in the flake

**Comment by mkenigs** [comment]
Closed by https://github.com/flox/floxpkgs/pull/88
